version: '3.9'
services:
    nginx:
        build:
            context: .
            dockerfile: docker/development/nginx/Dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php-fpm
        ports:
            - "8082:80"

    php-fpm:
        build:
            context: .
            dockerfile: docker/development/php-fpm/Dockerfile
        volumes:
            - ./src:/var/www/html

    php-cli:
        build:
            context: .
            dockerfile: docker/development/php-cli/Dockerfile
        volumes:
            - ./src:/var/www/html
            - composer:/root/.composer/cache
        tty: true

    node:
        image: node:12.7-alpine
        volumes:
            - ./src/:/var/www/html
        working_dir: /var/www/html/angular
        tty: true
        ports:
            - "8088:5000"


    redis:
        image: redis:5.0-alpine
        volumes:
            - redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'

    queue-redis:
        image: redis:5.0-alpine
        volumes:
            - queue-redis:/data

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: priceshape
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8081:80

#    manticore:
#        container_name: priceshape_manticore
##        image: manticoresearch/manticore:nodemode
#        build:
#            context: .
#            dockerfile: docker/development/manticore/Dockerfile
#        restart: always
#        ulimits:
#            nproc: 65535
#            nofile:
#                soft: 65535
#                hard: 65535
#            memlock:
#                soft: -1
#                hard: -1


volumes:
    redis:
    queue-redis:
    composer:
    dbdata:
