version: '3.7'
services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - "9876:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        image: mysql:5.7
        volumes:
            - mysql_test_volume:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=test"
            - "MYSQL_PASSWORD=test"
            - "MYSQL_DATABASE=test"
        ports:
            - "2345:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 3456:80
        links:
            - mysql
    node:
        build:
            context: .
            dockerfile: node/Dockerfile
        volumes:
            - ./:/var/www
        tty: true

volumes:
    mysql_test_volume:
