version: '2'
services:
    nginx:
        container_name: nginx
        build:
            context: docker
            dockerfile: nginx/nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:443"
        links:
            - php-fpm
    php-fpm:
        container_name: php
        build:
            context: docker
            dockerfile: php/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    node:
        container_name: node
        build:
            context: docker
            dockerfile: node/node.docker
        volumes:
            - ./:/var/www
        tty: true
