version: '3.7'
services:
    nginx:
        build:
            context: docker
            dockerfile: nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "????:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: docker
            dockerfile: php/Dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        image: mysql:5.7
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=?????"
            - "MYSQL_USER=?????"
            - "MYSQL_PASSWORD=?????"
            - "MYSQL_DATABASE=?????????????"
        ports:
            - "MYSQL_PORT:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - ????:80
        links:
            - mysql
    node:
        build:
            context: docker
            dockerfile: node/Dockerfile
        volumes:
            - ./:/var/www
        tty: true

volumes:
    mysql_volume:
